name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to jsonDB. Please provide us as many informations as posible. Thank you!'
        pr-message: 'Welcome to jsonDB. Please wait. We are looking you pull request through. Thank you!'
